### ISSUE TITLE
feature enhancement [feat]: view more comments

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Socialgram#14]
![image](https://user-images.githubusercontent.com/61280281/101066111-ffb2da80-35bb-11eb-9fd5-7c99f463d0d7.png)

- It shows this behavior when more comments are added.

Adding the feature of "View More Comments" after it exceeds 2-3 comments would work the best.

**Comment by sayna3311** [comment]
I would like to work on it. Please assign this to me.
