### ISSUE TITLE
feat: display the user who posts/comments

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Socialgram#15]
![image](https://user-images.githubusercontent.com/61280281/101066340-47d1fd00-35bc-11eb-9c5c-aa4ae8dd6b66.png)

Displaying the profile name, who posted, on top of the content in the post.

**Comment by Chaitanya31612** [comment]
I want to work on it.

**Comment by Chaitanya31612** [comment]
@shelcia as there is no pull request for so many days I'd like to know whether I can work on this?
