### ISSUE TITLE
disable multiple likes/dislikes

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Socialgram#16]
![image](https://user-images.githubusercontent.com/61280281/101066906-e3636d80-35bc-11eb-85e3-fb3d154f2884.png)

- When clicked multiple times, the counter increases. Now, I am not sure if it is supposed to be that way for the web app.
- Instead, we can have a click -> like, click again -> unlike feature.

**Comment by Chaitanya31612** [comment]
@shelcia I'd like to work on this issue.
