### ISSUE TITLE
Create code of conduct.md file

### ISSUE THREAD

**Issue by yashgautam9274** [shelcia/Socialgram#19]

**Comment by shelcia** [comment]
Yes add documentation

**Comment by yashgautam9274** [comment]
Ok

**Comment by p-soham11** [comment]
Hello 😃
Can I work on this ?

**Comment by yashgautam9274** [comment]
@p-soham11  bro i am already working on this 
you can work on other issue

**Comment by p-soham11** [comment]
Ok @yashgautam9274 , no problem.

@shelcia  can we create issues and work on them ?

**Comment by shelcia** [comment]
> Ok @yashgautam9274 , no problem.
> 
> @shelcia can we create issues and work on them ?

yes you can
