### ISSUE TITLE
Delete User completely

### ISSUE THREAD

**Issue by shelcia** [shelcia/Socialgram#219]

**Comment by AkashSharma001** [comment]
I would like to work on this issue.

@shelcia

**Comment by AkashSharma001** [comment]
I have seen the Backend of Socialgram, **DELETE** method is not implemented in the user API, so I can't delete the user.
First, I have to implement the **DELETE** method in the user API to the backend so that we can delete the user.

**Comment by shelcia** [comment]
yes that is the work. You can make two PRs.

**Comment by shelcia** [comment]
Changed this to hard as you will be sending two PRs to backend and frontend

**Comment by AkashSharma001** [comment]
I have made two PRs for the backend and frontend.
@shelcia

**Comment by shelcia** [comment]
@AkashSharma001  this will be part of KWOC as we this repo is not part of codepeak

**Comment by AkashSharma001** [comment]
Okay, I haven't registered for codepeak.
@shelcia

**Comment by 1010varun** [comment]
I would to wok on this issue.
@shelcia
