### ISSUE TITLE
Good homepage

### ISSUE THREAD

**Issue by shelcia** [shelcia/Socialgram#244]

**Comment by Bharadwajshivam28** [comment]
@shelcia Please assign this to me sir

**Comment by Bharadwajshivam28** [comment]
I will make a good homepage @shelcia

**Comment by Bharadwajshivam28** [comment]
sir i had made the homepage can i give picture here

**Comment by Bharadwajshivam28** [comment]
I had to recreate this page sir ?

**Comment by Bharadwajshivam28** [comment]
@shelcia

**Comment by Bharadwajshivam28** [comment]
I have recreated the homepage with the knowledge that i have @shelcia

**Comment by Bharadwajshivam28** [comment]
https://user-images.githubusercontent.com/108119109/217745082-ba4eebd9-35c0-4930-b826-dfa2c806695a.mp4

**Comment by Bharadwajshivam28** [comment]
I think this login page will be perfect for Socialgram as this login page will attract many @shelcia

**Comment by Bharadwajshivam28** [comment]
I am new in this field so i had knowledge only to make login page but i think this login page is perfect @shelcia

**Comment by Bharadwajshivam28** [comment]
I dont have much deep knowledge

**Comment by shelcia** [comment]
dont have to change login part, just add content beside it

**Comment by Bharadwajshivam28** [comment]
ok sir @shelcia

**Comment by Bharadwajshivam28** [comment]
can you just drop some words like what type of contents @shelcia

**Comment by Bharadwajshivam28** [comment]
@shelcia Mam i can use html ,css and js for content adding

**Comment by Nityamalviya28** [comment]
@shelcia plz assign me this issue .
I will make a good homepage according to your need.
