### ISSUE TITLE
Logo not matching

### ISSUE THREAD

**Issue by JasonDsouza212** [shelcia/Socialgram#263]
## The logo on the main page and the rest of the pages don't match 

![Screenshot from 2023-02-27 09-19-53](https://user-images.githubusercontent.com/74404894/221470283-615a25c5-142a-468f-92d6-1ba96eefeef3.png)
![Screenshot from 2023-02-27 09-19-32](https://user-images.githubusercontent.com/74404894/221470290-540a0be9-061c-4626-9900-87425ba2f8c9.png)

##  If you zoom in on the logo at the top, you can see that the logo has a capital G, but on the main page, it is not capitalized
![Screenshot from 2023-02-27 09-22-32](https://user-images.githubusercontent.com/74404894/221470449-8b67de44-989f-4aa8-b087-5c7423f354de.png)

## It would be best if the same logo is maintained everywhere.

**Comment by shelcia** [comment]
there's no logo, it was random

**Comment by JasonDsouza212** [comment]
Then you can make it Identical
SocialGram Or Socialgram
