### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by Kerveyfelix** [shelcia/Socialgram#28]
I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
Can I work on this?

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by shelcia** [comment]
> I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
> Can I work on this?

Hey i am closing all other issues i think it's redundant
