### ISSUE TITLE
Code of Conduct link not working

### ISSUE THREAD

**Issue by kavania2002** [shelcia/Socialgram#31]
In the Readme.md, the CoC not working.
Like to work on it.

**Comment by shelcia** [comment]
It is working dear

**Comment by kavania2002** [comment]
![Click](https://user-images.githubusercontent.com/72624080/101506919-f6e74d80-399b-11eb-95c8-78a15849b8b2.PNG)
![Screenshot (31)](https://user-images.githubusercontent.com/72624080/101506944-fe0e5b80-399b-11eb-9957-8085d6842a8d.png)

**Comment by kavania2002** [comment]
Then why am I getting this error??

**Comment by kavania2002** [comment]
And one more issue
Below is line of Readme.md
Take a look at the Existing Issue (on clicking on issue is directing me to issue some other site and not issues of this project)

**Comment by shelcia** [comment]
It works for me tho. I am closing this issue
