### ISSUE TITLE
bug: redirects to the pages without authentication

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Socialgram#33]
Here is something I noticed.

- The pages can be accessed without authentication.
- Without logging in, I opened https://socialgram.netlify.app/homepage 
- In fact, it also allows me to add a post, without logging in, but the post is not saved, once reloaded, but this should not how the webpage should behave.
- It happens so with all the pages, I tried to open https://socialgram.netlify.app/homepage/profile, it shows empty details, but it shows them.

![image](https://user-images.githubusercontent.com/61280281/101500795-f7301a80-3994-11eb-8ab0-6769bee626dd.png)

If any URL is accessed, and the user is not logged in, it should redirect them to - https://socialgram.netlify.app/

Another issue in reference to this: #34

**Comment by shelcia** [comment]
I am closing the issue the solution for the same could be address along with previous issue
