### ISSUE TITLE
bug: not redirecting to homepage 

### ISSUE THREAD

**Issue by tusharnankani** [shelcia/Socialgram#34]
In reference to #33 

- I opened https://socialgram.netlify.app
- I logged in.
- Redirects me to - https://socialgram.netlify.app/homepage
- Now, if I remove `homepage` from the URL, and run it again, it doesn't redirect me to the homepage, it takes me to the https://socialgram.netlify.app/ and I have to log in again.

This can be handled by checking if the user is logged in, then it should redirect them to https://socialgram.netlify.app/homepage.

**Comment by shelcia** [comment]
Yes i want to address this I forgot to add this part in code. Please make sure you do so with the tokens or if you have better way .. go ahead.
