### ISSUE TITLE
Ads section is not responsive after 552px

### ISSUE THREAD

**Issue by urvashi-code1255** [shelcia/Socialgram#35]
![facebookClone](https://user-images.githubusercontent.com/63122133/101504477-45dfb380-3999-11eb-955d-a0dc8329bbe0.PNG)

As shown in the picture, Ads section is not responsive after 552px . It is attached to left, there is no left margin at all.
@shelcia I want to work on this issue.

Thanks & Regards
Urvashi Anand

**Comment by shelcia** [comment]
Well It works good on phone tho

**Comment by shelcia** [comment]
And if you want to make it responsive what you gonna do with ads and side bar section ?

**Comment by urvashi-code1255** [comment]
@shelcia  Yeah  it works for phone but its Ad section is not having any left margin because of which it is difficult to see the Ad content in phone. So, I will give do it for Ad section of every page using Js.
