### ISSUE TITLE
Enhancement in individual post.

### ISSUE THREAD

**Issue by Chaitanya31612** [shelcia/Socialgram#44]
Following enhancements can be done to post component:
- Can have reaction bar like LinkedIn, Facebook etc which enables the user to give multiple reactions on hover over the like icon.
- Comment box should be improved like:
   - There should be a comment button and on click of this button, comment box should appear. This will not clutter the site and make it look a lot cleaner and userfriendly.
   - comment input field should be textarea as it is for the post.

**Comment by shelcia** [comment]
Why text area for comment ? anyway go ahead

**Comment by Chaitanya31612** [comment]
> Why text area for comment ? anyway go ahead

Just a UI enhancement feature as it maintains the flow of the website. Having a similar design for comment as for post often looks better.

**Comment by Atharvk7** [comment]
Hello @shelcia could you assign me this issue?

**Comment by Atharvk7** [comment]
@shelcia could you please elaborate the issue and expectations in UI?
