### ISSUE TITLE
Update imports and exports to ES6

### ISSUE THREAD

**Issue by paramsiddharth** [shelcia/Socialgram#45]
# Update all imports from traditional NodeJS `require` to ES6 imports and the same for exports
This is an update to the back-end.

Old:
``` node
const module = require('module'); // Default import
const portion = require('module').portion; // Not default import
```
New:
``` node
import { portion } from 'module'; // Not default import
import module from 'module'; // Default import
```

Similarly, update all `module.exports` to use ES6 exports.

Old:
``` node
module.exports = module; // Default export
exports.portion = portion; // Not default export
```
New:
``` node
export default module; // Default export
export portion; // Not default export
```

If approved, I would start working on this. This wouldn't affect the overall performance of the application much, but improve code readability by the usage of modern conventions.  
Also, not that this won't be backwards-compatible, though it is the recommended way to import and export in the modern versions of Node.js.

**Comment by shelcia** [comment]
Hey I don't think it's something very much necessary.
