### ISSUE TITLE
Users should be able to embed links(maybe a gist, medium article or youtube video) in their post

### ISSUE THREAD

**Issue by shelcia** [shelcia/Socialgram#6]

**Comment by paramsiddharth** [comment]
Does this issue require automatic URL recognition and tagging, or should there be a separate section for link in posts?

**Comment by shelcia** [comment]
Yes .. Sorry for the delayed reply

**Comment by Chaitanya31612** [comment]
@shelcia I'd like to add this feature if not done already.
