### ISSUE TITLE
Add Time stamp to posts

### ISSUE THREAD

**Issue by shelcia** [shelcia/Socialgram#9]

**Comment by snehaM2210** [comment]
I would like to work on this issue. Please assign it to me @shelcia .

**Comment by snehaM2210** [comment]
I'm sorry, I wasn't able to solve it..

**Comment by dijodaiju7** [comment]
I would like to work on this issue. Can you please assign it to me @shelcia .

**Comment by dijodaiju7** [comment]
Hi @shelcia Can I know how to perform the change on post time stamp issue. I've cloned the socialgram repo do i've to clone fb-backend repo.

**Comment by Chaitanya31612** [comment]
@shelcia can I work on this issue, I've done this before with moment.js, so I can do it easily.
